# Generated by Django 6.0.4 on 2026-04-24 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
    ]
