# Generated by Django 6.0.4 on 2026-05-23 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_escola'),
        ('escola', '0002_configuracaosistema_backupsistema_logsistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
        ),
    ]
