# Generated by Django 5.2.3 on 2025-06-26 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('emitido_em', models.DateField(auto_now_add=True)),
                ('aluno', models.OneToOneField(limit_choices_to={'perfil': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('ano_conclusao', models.CharField(max_length=4)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('emitido_em', models.DateField(auto_now_add=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'perfil': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Declaracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('emitida_em', models.DateField(auto_now_add=True)),
                ('conteudo', models.TextField()),
                ('aluno', models.ForeignKey(limit_choices_to={'perfil': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
