# Generated by Django 6.0.4 on 2026-04-24 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaoestudante',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificado',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declaracao',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
    ]
