# Generated by Django 5.2.3 on 2025-06-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='area_formacao',
            field=models.CharField(default='Desconhecido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nivel_academico',
            field=models.CharField(default='Desconhecido', max_length=100),
            preserve_default=False,
        ),
    ]
