# Generated by Django 5.2.3 on 2025-07-02 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0003_funcionario_area_formacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconfirmacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.CharField(max_length=9)),
                ('data', models.DateField(auto_now_add=True)),
                ('turno', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=10)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.aluno')),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracao.classe')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracao.curso')),
                ('sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracao.sala')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.turma')),
            ],
        ),
    ]
