# Generated by Django 5.2.2 on 2025-08-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0007_funcionario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='estado',
            field=models.CharField(choices=[('Adimplente', 'Adimplente'), ('Inadimplente', 'Inadimplente')], default='Adimplente', max_length=20),
        ),
    ]
