# Generated by Django 5.2.2 on 2025-08-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0008_aluno_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='estado',
        ),
        migrations.AddField(
            model_name='reconfirmacao',
            name='estado',
            field=models.CharField(choices=[('Adimplente', 'Adimplente'), ('Inadimplente', 'Inadimplente')], default='Adimplente', max_length=20),
        ),
    ]
