# Generated by Django 5.2.2 on 2025-08-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0009_remove_aluno_estado_reconfirmacao_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='anolectivo',
            name='estado',
            field=models.CharField(default='Aberto', max_length=50),
        ),
    ]
