# Generated by Django 5.2.2 on 2025-09-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0010_anolectivo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='ano_letivo',
            field=models.CharField(default=-1, max_length=9),
            preserve_default=False,
        ),
    ]
