# Generated by Django 5.2.2 on 2025-09-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0011_turma_ano_letivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconfirmacao',
            name='estadoClasse',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], default='Pendente', max_length=20),
        ),
    ]
