# Generated by Django 5.2.2 on 2025-09-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0012_reconfirmacao_estadoclasse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='bi',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
    ]
