# Generated by Django 5.2.8 on 2025-12-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0013_alter_aluno_bi'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Salário'),
        ),
    ]
