# Generated by Django 5.2.8 on 2025-12-19 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0014_funcionario_salario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DescontoFalta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_desconto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Desconto por Falta')),
            ],
        ),
        migrations.CreateModel(
            name='FaltaFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(help_text='Informe o mês da falta (1 a 12)', verbose_name='Mês')),
                ('dia', models.PositiveSmallIntegerField(verbose_name='Dia da Falta')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('ano_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas_funcionarios', to='administracao.anolectivo')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='administracao.funcionario')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Falta de Funcionário',
                'verbose_name_plural': 'Faltas de Funcionários',
                'ordering': ['-data_registro'],
                'unique_together': {('funcionario', 'ano_lectivo', 'mes', 'dia')},
            },
        ),
    ]
