# Generated by Django 5.2.8 on 2025-12-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0015_descontofalta_faltafuncionario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='faltafuncionario',
            unique_together=set(),
        ),
    ]
