# Generated by Django 5.2.8 on 2025-12-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0016_alter_faltafuncionario_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descontofalta',
            name='valor_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Desconto por Falta'),
        ),
    ]
