# Generated by Django 5.2.8 on 2026-02-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0017_alter_descontofalta_valor_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='ano_nasc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='dia_nasc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='mes_nasc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_mae',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_pai',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
