# Generated by Django 5.2.8 on 2026-02-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0018_aluno_ano_nasc_aluno_dia_nasc_aluno_mes_nasc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='naturalidade',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
