# Generated by Django 6.0.4 on 2026-04-24 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0019_aluno_naturalidade'),
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anolectivo',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classe',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='descontofalta',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faltafuncionario',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconfirmacao',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
    ]
