# Generated by Django 6.0.4 on 2026-04-24 14:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0020_aluno_escola_anolectivo_escola_classe_escola_and_more'),
        ('escola', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='escola',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='escolas',
            field=models.ManyToManyField(related_name='funcionarios', to='escola.escola', verbose_name='Escolas'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='area_formacao',
            field=models.CharField(max_length=100, verbose_name='Área de Formação'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(choices=[('Diretor Geral', 'Diretor Geral'), ('Diretor Pedagógico', 'Diretor Pedagógico'), ('Diretor Administrativo', 'Diretor Administrativo'), ('Coordenador de Turno', 'Coordenador de Turno'), ('Coordenador de Turma', 'Coordenador de Turma'), ('Coordenador de Disciplina', 'Coordenador de Disciplina'), ('Secretário Geral', 'Secretário Geral'), ('Secretário Administrativo', 'Secretário Administrativo'), ('Secretário Pedagógico', 'Secretário Pedagógico'), ('Professor', 'Professor'), ('Auxiliar Administrativo', 'Auxiliar Administrativo'), ('Auxiliar de Limpeza', 'Auxiliar de Limpeza'), ('Segurança', 'Segurança'), ('Motorista', 'Motorista'), ('Outro', 'Outro')], max_length=100, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nivel_academico',
            field=models.CharField(max_length=100, verbose_name='Nível Acadêmico'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario', to=settings.AUTH_USER_MODEL),
        ),
    ]
