# Generated by Django 6.0.4 on 2026-05-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0021_alter_funcionario_options_remove_funcionario_escola_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
