# Generated by Django 6.0.4 on 2026-05-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0022_curso_tipo'),
        ('escola', '0002_configuracaosistema_backupsistema_logsistema'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reconfirmacao',
            index=models.Index(fields=['escola'], name='administrac_escola__74417f_idx'),
        ),
        migrations.AddIndex(
            model_name='reconfirmacao',
            index=models.Index(fields=['aluno'], name='administrac_aluno_i_61743c_idx'),
        ),
        migrations.AddIndex(
            model_name='reconfirmacao',
            index=models.Index(fields=['ano_letivo'], name='administrac_ano_let_540b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='reconfirmacao',
            index=models.Index(fields=['estado'], name='administrac_estado_0c37cb_idx'),
        ),
        migrations.AddIndex(
            model_name='reconfirmacao',
            index=models.Index(fields=['escola', 'ano_letivo'], name='administrac_escola__41081b_idx'),
        ),
        migrations.AddIndex(
            model_name='reconfirmacao',
            index=models.Index(fields=['aluno', 'ano_letivo'], name='administrac_aluno_i_83cbee_idx'),
        ),
    ]
