# Generated by Django 6.0.4 on 2026-04-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('decreto_executivo', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('nif', models.CharField(max_length=50, null=True, unique=True)),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('contacto', models.CharField(max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
