# Generated by Django 6.0.4 on 2026-05-17 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sistema', models.CharField(default='SIGESC - Sistema Integrado de Gestão Escolar', max_length=255)),
                ('ano_lectivo_corrente', models.CharField(blank=True, max_length=9, null=True)),
                ('timezone', models.CharField(default='Africa/Luanda', max_length=50)),
                ('backup_auto', models.BooleanField(default=False)),
                ('backup_frequencia', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], default='daily', max_length=20)),
                ('manter_backups_dias', models.IntegerField(default=30)),
                ('smtp_server', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('email_sistema', models.EmailField(blank=True, max_length=254)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackupSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('caminho', models.CharField(max_length=500)),
                ('tamanho', models.CharField(blank=True, max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('info', 'Informação'), ('warning', 'Aviso'), ('error', 'Erro'), ('success', 'Sucesso')], default='info', max_length=20)),
                ('detalhes', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
