from django.urls import path
from . import views

app_name = 'core'


urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('selecionar-escola/selecionar/', views.selecionar_escola, name='selecionar_escola'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('usuarios/', views.usuarios, name='usuarios'),
    path('verificar-acao/', views.verificar_acao_usuario, name='verificar_acao_usuario'),
    path('funcionarios/', views.cadastrar_funcionario, name='cadastrar_funcionario'),
    path('confirmar-acao-funcionario/', views.confirmar_acao_funcionario, name='confirmar_acao_funcionario'),
    path('excluir-funcionario/', views.excluir_funcionario, name='excluir_funcionario'),
    path('professor/<int:professor_id>/vinculo/', views.vinculo_docente, name='vinculo_professor'),
    path('professor/<int:professor_id>/vincular/editar/<int:vinculo_id>/', views.vinculo_docente, name='editar_vinculo_docente'),
    path('professor-vinculo/excluir/<int:vinculo_id>/', views.excluir_vinculo_docente, name='excluir_vinculo_docente'),
    path('docentes/', views.docentes, name='docentes'),
    path('docente/<int:id>/detalhes/', views.detalhes_professor, name='detalhes_professor'),
    path('editar-funcionario/<int:funcionario_id>/', views.editar_funcionario, name='editar_funcionario'),
    path('alunos-lista/', views.alunos, name='alunos_lista'),
    path('alunos/editar/<int:aluno_id>/', views.editar_aluno, name='editar_aluno'),
    path('aluno/<int:id>/', views.aluno_detalhes, name='aluno_detalhes'),
    path('aluno/<int:id>/upload-foto/', views.upload_foto_aluno, name='upload_foto_aluno'),
    path('deletar-nota/', views.deletar_nota, name='deletar_nota'),
    path('classes/', views.classes, name='classes'),
    path('classes/criar/', views.criar_classe, name='criar_classe'),
    path('classes/atualizar/', views.atualizar_classe, name='atualizar_classe'),
    path('classes/eliminar/<int:id>/', views.eliminar_classe, name='eliminar_classe'),
    path('cursos/', views.cursos, name='cursos'),
    path('cursos/criar/', views.criar_curso, name='criar_curso'), 
    path('cursos/atualizar/', views.atualizar_curso, name='atualizar_curso'),
    path('cursos/eliminar/<int:id>/', views.eliminar_curso, name='eliminar_curso'),
    path('turma-salas/', views.turmas_e_salas, name='turmas_e_salas'),
    path('turmas/criar/', views.criar_turma, name='criar_turma'),
    path('turmas/editar/', views.editar_turma, name='editar_turma'),
    path('turmas/excluir/<int:turma_id>/', views.eliminar_turma, name='excluir_turma'), 
    path('disciplinas/', views.listar_disciplinas, name='disciplinas'),
    path('disciplinas/criar/', views.criar_disciplina, name='criar_disciplina'),
    path('disciplinas/<int:id>/editar/', views.editar_disciplina, name='editar_disciplina'),
    path('disciplinas/<int:id>/eliminar/', views.deletar_disciplina, name='deletar_disciplina'),
    path('disciplinas-classes/criar/', views.criar_vinculo, name="criar_vinculo"),
    path('disciplinas-classes/editar/<int:pk>/', views.editar_vinculo, name="editar_vinculo"),
    path('disciplinas-classes/excluir/<int:pk>/', views.excluir_vinculo, name="excluir_vinculo"),
    path('disciplinas/<int:id>/editar/', views.editar_disciplina, name='editar_disciplina'),
    path('disciplinas/<int:id>/eliminar/', views.deletar_disciplina, name='deletar_disciplina'),
    path('matriculas/', views.matriculas_view, name='matriculas'),
    path('pautas/', views.pautas, name='pautas'), 
    path('coordenacoes/', views.coordenacoes, name='coordenacoes'),
    path('coordenacoes/criar/', views.criar_coordenacao, name='criar_coordenacao'),
    path('coordenacoes/editar/<int:pk>/', views.editar_coordenacao, name='editar_coordenacao'),
    path('coordenacoes/eliminar/<int:pk>/', views.eliminar_coordenacao, name='eliminar_coordenacao'),
    path("alterar-senha/", views.alterar_senha, name="alterar_senha"),
    path("ano-lectivo/", views.ano_lectivo, name='ano_lectivo'),
] 
 