# Generated by Django 5.2.3 on 2025-06-26 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('classe', models.IntegerField()),
                ('codigo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_lectivo', models.CharField(max_length=9)),
                ('reconfirmada', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.IntegerField(choices=[(1, '1º'), (2, '2º'), (3, '3º')])),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogico.disciplina')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogico.matricula')),
            ],
        ),
    ]
