# Generated by Django 5.2.3 on 2025-06-26 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_initial'),
        ('pedagogico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorVinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogico.disciplina')),
                ('professor', models.ForeignKey(limit_choices_to={'funcao': 'professor'}, on_delete=django.db.models.deletion.CASCADE, to='administracao.funcionario')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.turma')),
            ],
        ),
    ]
