# Generated by Django 5.2.2 on 2025-07-23 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0004_reconfirmacao'),
        ('pedagogico', '0002_professorvinculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='matricula',
        ),
        migrations.AddField(
            model_name='nota',
            name='aluno',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='administracao.aluno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administracao.classe'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
