# Generated by Django 5.2.2 on 2025-07-24 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0005_anolectivo'),
        ('pedagogico', '0003_remove_nota_matricula_nota_aluno_nota_classe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='ano_lectivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administracao.anolectivo'),
            preserve_default=False,
        ),
    ]
