# Generated by Django 5.2.2 on 2025-07-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0004_nota_ano_lectivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='trimestre',
            field=models.IntegerField(choices=[(1, '1º'), (2, '2º'), (3, '3º'), (4, 'exame')]),
        ),
    ]
