# Generated by Django 5.2.2 on 2025-07-25 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0005_anolectivo'),
        ('pedagogico', '0005_alter_nota_trimestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinasClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.classe')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogico.disciplina')),
            ],
        ),
    ]
