# Generated by Django 5.2.2 on 2025-08-04 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0006_aluno_foto'),
        ('pedagogico', '0006_disciplinasclasse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('turno', 'Coordenador de Turno'), ('turma', 'Coordenador de Turma'), ('disciplina', 'Coordenador de Disciplina')], max_length=15)),
                ('turno', models.CharField(blank=True, choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=10, null=True)),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedagogico.disciplina')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.funcionario')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracao.turma')),
            ],
            options={
                'verbose_name': 'Coordenação',
                'verbose_name_plural': 'Coordenações',
                'unique_together': {('funcionario', 'tipo', 'turno', 'turma', 'disciplina')},
            },
        ),
    ]
