# Generated by Django 5.2.8 on 2025-12-23 10:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0007_coordenacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('resumo', models.TextField(blank=True, null=True, verbose_name='Resumo')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('autor_curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('autor_telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('autor_email', models.EmailField(max_length=100, verbose_name='Email')),
                ('orientador', models.CharField(max_length=100, verbose_name='Orientador')),
                ('orientador_telefone', models.CharField(max_length=20, verbose_name='Telefone do Orientador')),
                ('arquivo', models.FileField(upload_to='monografias/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='Arquivo')),
                ('ano_academico', models.CharField(max_length=9, verbose_name='Ano Académico')),
                ('data_submissao', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('rascunho', 'Rascunho'), ('submetido', 'Submetido'), ('avaliacao', 'Em Avaliação'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='avaliacao', max_length=20)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliador', models.CharField(max_length=100, verbose_name='Avaliador')),
                ('data_atribuicao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('parecer', models.TextField(blank=True, verbose_name='Parecer')),
                ('recomendacao', models.CharField(blank=True, choices=[('aprovado', 'Aprovar'), ('reprovado', 'Reprovar'), ('correcoes', 'Necessita Correções')], max_length=20)),
                ('monografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='pedagogico.monografia')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data_atribuicao'],
            },
        ),
    ]
