# Generated by Django 5.2.8 on 2026-01-20 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0008_monografia_avaliacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professorvinculo',
            options={'verbose_name': 'Vínculo de Professor', 'verbose_name_plural': 'Vínculos de Professores'},
        ),
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('2', 'Segunda-feira'), ('3', 'Terça-feira'), ('4', 'Quarta-feira'), ('5', 'Quinta-feira'), ('6', 'Sexta-feira'), ('7', 'Sábado')], max_length=1)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('tempo_aula', models.PositiveIntegerField(help_text='Ex: 1 para primeiro tempo')),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='pedagogico.professorvinculo')),
            ],
            options={
                'verbose_name': 'Horário de Aula',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
