# Generated by Django 6.0.4 on 2026-04-24 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
        ('pedagogico', '0009_alter_professorvinculo_options_horarioaula'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordenacao',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplina',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplinasclasse',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monografia',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professorvinculo',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
    ]
