from django.urls import path
from . import views

app_name = 'pedagogico'

urlpatterns = [ 
    path('', views.dashboard, name='dashboard'),
    path('logout/', views.logout_view, name='logout'),
    path('docentes/', views.docentes, name='docentes'),
    path('docente/<int:id>/detalhes/', views.detalhes_professor, name='detalhes_professor'),
    path('disciplinas/', views.listar_disciplinas, name='disciplinas'),
    path('disciplinas/criar/', views.criar_disciplina, name='criar_disciplina'),
    path('disciplinas/<int:id>/editar/', views.editar_disciplina, name='editar_disciplina'),
    path('disciplinas/<int:id>/eliminar/', views.deletar_disciplina, name='deletar_disciplina'),
    path('disciplinas-classes/criar/', views.criar_vinculo, name="criar_vinculo"),
    path('disciplinas-classes/editar/<int:pk>/', views.editar_vinculo, name="editar_vinculo"),
    path('disciplinas-classes/excluir/<int:pk>/', views.excluir_vinculo, name="excluir_vinculo"),
    path('professor/<int:professor_id>/vinculo/', views.vinculo_docente, name='vinculo_professor'),
    path('matriculas/', views.matriculas_view, name='matriculas'),
    path('turma-salas/', views.turmas_e_salas, name='turmas_e_salas'),
    path('turmas/criar/', views.criar_turma, name='criar_turma'),
    path('turmas/editar/', views.editar_turma, name='editar_turma'),
    path('turmas/excluir/<int:turma_id>/', views.eliminar_turma, name='excluir_turma'),
    path('alunos-lista/', views.alunos, name='alunos_lista'),
    path('aluno/<int:id>/', views.aluno_detalhes, name='aluno_detalhes'),
    path('pautas/', views.pautas, name='pautas'), 
    path('pautas/<int:trimestre>/', views.pautas_trimestre, name='pautas_trimestre'),
    path('pautas/final/', views.pautas_final, name='pautas_finais'),
    path('lancar-nota/', views.lancar_nota, name='lancar_nota'), 
    path('aluno/<int:id>/upload-foto/', views.upload_foto_aluno, name='upload_foto_aluno'),
    path('editar-nota/', views.editar_nota, name='editar_nota'),
    path('coordenacoes/', views.coordenacoes, name='coordenacoes'),
    path('coordenacoes/criar/', views.criar_coordenacao, name='criar_coordenacao'),
    path('coordenacoes/editar/<int:pk>/', views.editar_coordenacao, name='editar_coordenacao'),
    path('coordenacoes/eliminar/<int:pk>/', views.eliminar_coordenacao, name='eliminar_coordenacao'),
    path('reconfirmacao/', views.reconfirmacao, name='reconfirmacao'),
     path('monografias-lista/', views.monografias, name='monografias'),
    path('avaliacoes/', views.avaliacoes, name='avaliacoes'),
    path('editar-monografia/<int:monografia_id>/', views.editar_monografia, name='editar_monografia'),
    path('atualizar-monografia/<int:monografia_id>/', views.atualizar_monografia, name='atualizar_monografia'),
    path('detalhes-monografia/<str:monografia_id>/', views.detalhe_monografia, name='detalhe_monografia'),
    path('salvar/', views.salvar_monografia, name='salvar_monografia'),
    path('excluir-monografia/<int:monografia_id>/', views.excluir_monografia, name='excluir_monografia'),
    path('monografia/<int:monografia_id>/avaliar/', views.submeter_avaliacao, name='submeter_avaliacao'),
    path('relatorio-pedagogico/', views.relatorio_pedagogico, name='relatorio_pedagogico'),
] 
