# Generated by Django 5.2.2 on 2025-08-14 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_mesespagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='mes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financeiro.mesespagar'),
            preserve_default=False,
        ),
    ]
