# Generated by Django 5.2.2 on 2025-08-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_pagamento_mes'),
    ]

    operations = [
    ]
