# Generated by Django 5.2.2 on 2025-08-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_auto_20250814_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopagamento',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
