# Generated by Django 5.2.2 on 2025-08-14 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_alter_tipopagamento_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='tipoServico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.emolumentos'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='mes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.mesespagar'),
        ),
    ]
