# Generated by Django 5.2.2 on 2025-08-18 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_pagamento_tiposervico_alter_pagamento_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicar_multa', models.BooleanField(default=False)),
                ('data_aplicacao', models.PositiveSmallIntegerField(help_text='Dia do mês em que a multa deve ser aplicada (1-31)')),
                ('valor_multa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emolumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='financeiro.emolumentos')),
            ],
        ),
    ]
