# Generated by Django 5.2.2 on 2025-08-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_multa'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesespagar',
            name='numero',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
