# Generated by Django 5.2.8 on 2025-12-19 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_mesespagar_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('categoria', models.CharField(choices=[('salarios', 'Salários'), ('material', 'Material Escolar'), ('manutencao', 'Manutenção'), ('energia', 'Energia/Água'), ('internet', 'Internet/Telefone'), ('alimentacao', 'Alimentação'), ('transportes', 'Transportes'), ('limpeza', 'Limpeza'), ('outros', 'Outros')], default='outros', max_length=20)),
                ('data_despesa', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Despesa')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('registro_por', models.CharField(max_length=100, verbose_name='Responsável pela Despesa')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/despesas/', verbose_name='Comprovante')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data_despesa'],
            },
        ),
    ]
