# Generated by Django 5.2.8 on 2025-12-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='ano_lectivo',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=20),
        ),
    ]
