# Generated by Django 6.0.4 on 2026-04-24 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
        ('financeiro', '0012_despesa_ano_lectivo_alter_despesa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emolumentos',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mesespagar',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multa',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamento',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recibo',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipopagamento',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='escola.escola'),
            preserve_default=False,
        ),
    ]
