# Generated by Django 6.0.4 on 2026-04-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_despesa_escola_emolumentos_escola_mesespagar_escola_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesespagar',
            name='numero',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
